server.port: 8443

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/techtest?serverTimezone=UTC
    username: root
    password: pass

  jpa:
    hibernate:
        ddl-auto: update
