server.port: 8443

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/techtest?serverTimezone=UTC
    username: root
    password: pass

  jpa:
    hibernate:
        ddl-auto: update

cloudinary:
  url: https://api.cloudinary.com
  cloudName: techtest
  apiKey: asdasd123123
  secret: 123123asdasd
